name: Hub
version: '1.0-SNAPSHOT'
main: cf.electrich.hub.Main
authors: [ Compromissed ]
commands:
  spawn:
    description: Easily teleport to Spawn.
  gamemode:
    description: Change your or other player gamemode.
    aliases: ['gm', 'gmode']